<?php
/**
 *
 * NOTICE OF LICENSE
 *
 * This file is subject to the license
 * that is bundled with this package in the file LICENSE_Temgra.txt.
 * If you did not receive a copy of the license, please send an email
 * to info@temgra.com so we can send you a copy immediately.
 *
 * @copyright Copyright (c) 2009-2011 by Tania Alekova, temgra.com - Templates and Graphics Online Store (http://www.temgra.com) - All rights reserved.
 * @license   http://www.temgra.com/license
 * 
 */
?>
<?php $_product = $this->getProduct() ?>
<?php $_id = $_product->getId() ?>
<?php $simplePricesTax = ($this->helper('tax')->displayPriceIncludingTax() || $this->helper('tax')->displayBothPrices()); ?>
<?php $_minimalPriceValue = $_product->getMinimalPrice() ?>
<?php $_minimalPrice = $this->helper('tax')->getPrice($_product, $_minimalPriceValue, $simplePricesTax) ?>
<?php if (!$_product->isGrouped()): ?>
    <div class="price-box">
    <?php $_price = $this->helper('tax')->getPrice($_product, $_product->getPrice()) ?>
    <?php $_regularPrice = $this->helper('tax')->getPrice($_product, $_product->getPrice(), $simplePricesTax) ?>
    <?php $_finalPrice = $this->helper('tax')->getPrice($_product, $_product->getFinalPrice()) ?>
    <?php $_finalPriceInclTax = $this->helper('tax')->getPrice($_product, $_product->getFinalPrice(), true) ?>
    <?php if ($_finalPrice == $_price): ?>
        <?php if ($this->helper('tax')->displayBothPrices() && $_finalPriceInclTax != $_finalPrice): ?>
            <span class="price-excluding-tax">                
                <span class="price" id="price-excluding-tax-<?php echo $_id ?><?php echo $this->getIdSuffix() ?>"><?php echo Mage::helper('core')->currency($_price,true,false) ?></span>
                <span class="label"><?php echo Mage::helper('tax')->__('Price Excl. Tax:') ?></span>
            </span>
            <span class="price-including-tax">
                <span class="price" id="price-including-tax-<?php echo $_id ?><?php echo $this->getIdSuffix() ?>"><?php echo Mage::helper('core')->currency($_finalPriceInclTax,true,false) ?></span>
                <span class="label"><?php echo Mage::helper('tax')->__('Price Incl. Tax:') ?></span>
            </span>
        <?php else: ?>
        <span class="regular-price" id="product-price-<?php echo $_id ?><?php echo $this->getIdSuffix() ?>"><?php echo Mage::helper('core')->currency($_price,true,true) ?></span>
        <?php endif; ?>
    <?php else: ?>
        <p class="old-price">
            <span class="price-label"><?php echo $this->__('Regular Price:') ?></span>
            <span class="price" id="old-price-<?php echo $_id ?><?php echo $this->getIdSuffix() ?>"><?php echo Mage::helper('core')->currency($_regularPrice,true,false) ?></span>
        </p>
        <?php if ($this->helper('tax')->displayBothPrices() && $_finalPriceInclTax != $_finalPrice): ?>
            <p class="special-price">
                <span class="price-label"><?php echo $this->__('Special Price:') ?></span>
                <span class="price-excluding-tax">                    
                    <span class="price" id="price-excluding-tax-<?php echo $_id ?><?php echo $this->getIdSuffix() ?>"><?php echo Mage::helper('core')->currency($_finalPrice,true,false) ?></span>
                    <span class="label"><?php echo Mage::helper('tax')->__('Price Excl. Tax:') ?></span>
                </span>
            <span class="price-including-tax">
                <span class="price" id="price-including-tax-<?php echo $_id ?><?php echo $this->getIdSuffix() ?>"><?php echo Mage::helper('core')->currency($_finalPriceInclTax,true,false) ?></span>
                <span class="label"><?php echo Mage::helper('tax')->__('Price Incl. Tax:') ?></span>
            </span>
            </p>
        <?php else: ?>
        <p class="special-price">
            <span class="price-label"><?php echo $this->__('Special Price:') ?></span>
            <span class="price" id="product-price-<?php echo $_id ?><?php echo $this->getIdSuffix() ?>"><?php echo Mage::helper('core')->currency($_finalPrice,true,false) ?></span>
        </p>
        <?php endif; ?>
    <?php endif; ?>
    <?php if ($this->getDisplayMinimalPrice() && $_minimalPriceValue && $_minimalPriceValue < $_product->getFinalPrice()): ?>
        <a href="<?php echo $_product->getProductUrl(); ?>" class="minimal-price-link">
            <span class="label"><?php echo $this->__('As low as:') ?></span>
            <span class="price" id="product-minimal-price-<?php echo $_id ?><?php echo $this->getIdSuffix() ?>"><?php echo Mage::helper('core')->currency($_minimalPrice,true,false) ?></span>
        </a>
    <?php endif; ?>
    </div>
<?php else: ?>
    <?php
    $_exclTax = $this->helper('tax')->getPrice($_product, $_minimalPriceValue, $includingTax = null);
    $_inclTax = $this->helper('tax')->getPrice($_product, $_minimalPriceValue, $includingTax = true);
    ?>
    <?php if ($this->getDisplayMinimalPrice() && $_minimalPriceValue): ?>
        <div class="price-box">
            <span class="label"><?php echo $this->__('Starting at:') ?></span>
            <?php if ($this->helper('tax')->displayBothPrices() && ($_exclTax !== $_inclTax)): ?>
                <span class="price-excluding-tax">
                    <span class="price" id="price-excluding-tax-<?php echo $_id ?><?php echo $this->getIdSuffix() ?>"><?php echo Mage::helper('core')->currency($_exclTax, true, false) ?></span>
                    <span class="label"><?php echo Mage::helper('tax')->__('Price Excl. Tax:') ?></span>
                </span>
                <span class="price-including-tax">
                    <span class="price" id="price-including-tax-<?php echo $_id ?><?php echo $this->getIdSuffix() ?>"><?php echo Mage::helper('core')->currency($_inclTax, true, false) ?></span>
                    <span class="label"><?php echo Mage::helper('tax')->__('Price Incl. Tax:') ?></span>
                </span>
            <?php else: ?>
                <?php
                $_showPrice = $_inclTax;
                if (!$this->helper('tax')->displayPriceIncludingTax()) {
                    $_showPrice = $_exclTax;
                }
                ?>
            <span class="price" id="product-minimal-price-<?php echo $_id ?><?php echo $this->getIdSuffix() ?>"><?php echo Mage::helper('core')->currency($_showPrice, true, false) ?></span>
            <?php endif; ?>
        </div>
    <?php endif; ?>
<?php endif; ?>